# Generated by Django 6.0.3 on 2026-04-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_reviews/')),
                ('rating', models.IntegerField(default=5)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
