# Generated by Django 6.0.3 on 2026-03-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='token_or_table',
        ),
    ]
