# Generated by Django 6.0.3 on 2026-03-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_systemsettings_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
    ]
